# Site Settings
title: Working Drafts
email: tmfayle@uh.edu
description: >
  Essays in progress by Taylor Fayle
baseurl: ""
url: "http://localhost:4000"
twitter_username: taylorfayle
github_username:  taylorfayle
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
